### ISSUE TITLE
Websites are wrongly sorted

### ISSUE THREAD

**Issue by matthiasdusch** [OGGM/mb_crossval#11]
Sorting the websites does not work in human readable fashion.

e.g.: 1.0.2+104. does come before 1.0.2+23.

Should be easy to fix, but I'll probably overhaul the whole website generation algorithm soon anyway and will take care of this as well.

**Comment by fmaussion** [comment]
Do you have a way to parse the date of the commit? it would be much nicer than the cryptic names anyway. Maybe it would be good to have this info directly in OGGM as well, cc @TimoRoth

**Comment by TimoRoth** [comment]
Ideally you'd have a version like 1.0.2+104-g1234abc, so you can jump right to the commit in question, but still have proper sorting. I'm doing date based versions on anaconda, and it's a mess I should have never started.

**Comment by matthiasdusch** [comment]
closed by #13
